use_frameworks!

platform :ios, '12.0'

target 'AigensSdkCore_Example' do
  pod 'AigensSdkCore', :path => '../'
  pod 'AigensSdkApplepay', '0.0.8'

  target 'AigensSdkCore_Tests' do
    inherit! :search_paths

    
  end
end
